name = "gist-scheduler"
main = "list_gists.js"
compatibility_date = "2024-01-01"

[vars]
# Add any static variables here

# Add your GitHub token as a secret in the Cloudflare dashboard
# wrangler secret put GITHUB_TOKEN 